# Generated by Django 3.2.12 on 2022-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=250)),
                ('Dimg', models.ImageField(upload_to='pictures')),
                ('Ddes', models.TextField()),
            ],
        ),
    ]
